use_frameworks!

platform :ios, '8.0'

target 'AUpdater_Example' do
  pod 'AUpdater', :path => '../'

  target 'AUpdater_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
